-- ============================================================================
-- Temple of the Great Kasutamaiza
-- Passcode / Custom ID: 50000111
-- Type: [Spell / Normal]
-- Duelingbook Reference: https://www.duelingbook.com/card?id=1519175
-- Auto-generated by Yu-Gi-Oh Story Platform Lua Generator
-- ============================================================================
local s, id = GetID()

function s.initial_effect(c)
	-- Effect 1: When this card is activated: You can target 1 "Kasutama...
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(id,0))
	e1:SetCategory(CATEGORY_REMOVE)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e1:SetTarget(s.target1)
	e1:SetOperation(s.operation1)
	c:RegisterEffect(e1)

	-- Effect 2: You can activate the following effect(s), based on the ...
	local e2=Effect.CreateEffect(c)
	e2:SetDescription(aux.Stringid(id,1))
	e2:SetCategory(0)
	e2:SetType(EFFECT_TYPE_IGNITION)
	e2:SetTarget(s.target2)
	e2:SetOperation(s.operation2)
	c:RegisterEffect(e2)

	-- Effect 3: ● DIVINE Divine-Beast: Once per turn, during your Main ...
	local e3=Effect.CreateEffect(c)
	e3:SetDescription(aux.Stringid(id,2))
	e3:SetCategory(0)
	e3:SetType(EFFECT_TYPE_IGNITION)
	e3:SetCountLimit(1)
	e3:SetTarget(s.target3)
	e3:SetOperation(s.operation3)
	c:RegisterEffect(e3)

	-- Effect 4: ● Non-DIVINE: Once per turn: You can send up to 3 cards...
	local e4=Effect.CreateEffect(c)
	e4:SetDescription(aux.Stringid(id,3))
	e4:SetCategory(CATEGORY_REMOVE+CATEGORY_DESTROY)
	e4:SetType(EFFECT_TYPE_IGNITION)
	e4:SetCountLimit(1)
	e4:SetTarget(s.target4)
	e4:SetOperation(s.operation4)
	c:RegisterEffect(e4)

	-- Effect 5: ● "Kasutamaiza": Before damage calculation, if a monste...
	local e5=Effect.CreateEffect(c)
	e5:SetDescription(aux.Stringid(id,4))
	e5:SetCategory(0)
	e5:SetType(EFFECT_TYPE_IGNITION)
	e5:SetTarget(s.target5)
	e5:SetOperation(s.operation5)
	c:RegisterEffect(e5)

	-- Effect 6: You can only activate 1 "Temple of the Great Kasutamaiz...
	local e6=Effect.CreateEffect(c)
	e6:SetDescription(aux.Stringid(id,5))
	e6:SetCategory(0)
	e6:SetType(EFFECT_TYPE_IGNITION)
	e6:SetTarget(s.target6)
	e6:SetOperation(s.operation6)
	c:RegisterEffect(e6)
end

function s.target1(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return true end
end
function s.operation1(e,tp,eg,ep,ev,re,r,rp)
	-- Effect implementation
end

function s.target2(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return true end
end
function s.operation2(e,tp,eg,ep,ev,re,r,rp)
	-- Effect implementation
end

function s.target3(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return true end
end
function s.operation3(e,tp,eg,ep,ev,re,r,rp)
	-- Effect implementation
end

function s.target4(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return true end
end
function s.operation4(e,tp,eg,ep,ev,re,r,rp)
	-- Effect implementation
end

function s.target5(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return true end
end
function s.operation5(e,tp,eg,ep,ev,re,r,rp)
	-- Effect implementation
end

function s.target6(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return true end
end
function s.operation6(e,tp,eg,ep,ev,re,r,rp)
	-- Effect implementation
end
