-- ============================================================================
-- Mohousha the Accursed of the Great Kasutamaiza
-- Passcode / Custom ID: 50000106
-- Type: [Monster / Effect]
-- Duelingbook Reference: https://www.duelingbook.com/card?id=2624212
-- Auto-generated by Yu-Gi-Oh Story Platform Lua Generator
-- ============================================================================
local s, id = GetID()

function s.initial_effect(c)
	-- Effect 1: "Formless the True Void of Creation" + "The Void of Cre...
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(id,0))
	e1:SetCategory(0)
	e1:SetType(EFFECT_TYPE_IGNITION)
	e1:SetRange(LOCATION_MZONE)
	e1:SetTarget(s.target1)
	e1:SetOperation(s.operation1)
	c:RegisterEffect(e1)

	-- Effect 2: Must first be Special Summoned (from your Extra Deck) b...
	local e2=Effect.CreateEffect(c)
	e2:SetDescription(aux.Stringid(id,1))
	e2:SetCategory(CATEGORY_SPECIAL_SUMMON)
	e2:SetType(EFFECT_TYPE_IGNITION)
	e2:SetRange(LOCATION_MZONE)
	e2:SetTarget(s.target2)
	e2:SetOperation(s.operation2)
	c:RegisterEffect(e2)

	-- Effect 3: Once per turn: You can target 1 monster on the field; e...
	local e3=Effect.CreateEffect(c)
	e3:SetDescription(aux.Stringid(id,2))
	e3:SetCategory(0)
	e3:SetType(EFFECT_TYPE_IGNITION)
	e3:SetRange(LOCATION_MZONE)
	e3:SetCountLimit(1)
	e3:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e3:SetTarget(s.target3)
	e3:SetOperation(s.operation3)
	c:RegisterEffect(e3)

	-- Effect 4: If this card would leave the field, you can banish the ...
	local e4=Effect.CreateEffect(c)
	e4:SetDescription(aux.Stringid(id,3))
	e4:SetCategory(CATEGORY_REMOVE)
	e4:SetType(EFFECT_TYPE_IGNITION)
	e4:SetRange(LOCATION_MZONE)
	e4:SetTarget(s.target4)
	e4:SetOperation(s.operation4)
	c:RegisterEffect(e4)

	-- Effect 5: You can only control 1 "Mohousha the Accursed of the Gr...
	local e5=Effect.CreateEffect(c)
	e5:SetDescription(aux.Stringid(id,4))
	e5:SetCategory(0)
	e5:SetType(EFFECT_TYPE_IGNITION)
	e5:SetRange(LOCATION_MZONE)
	e5:SetTarget(s.target5)
	e5:SetOperation(s.operation5)
	c:RegisterEffect(e5)
end

function s.target1(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return true end
end
function s.operation1(e,tp,eg,ep,ev,re,r,rp)
	-- Effect implementation
end

function s.target2(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return true end
end
function s.operation2(e,tp,eg,ep,ev,re,r,rp)
	-- Effect implementation
end

function s.target3(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return true end
end
function s.operation3(e,tp,eg,ep,ev,re,r,rp)
	-- Effect implementation
end

function s.target4(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return true end
end
function s.operation4(e,tp,eg,ep,ev,re,r,rp)
	-- Effect implementation
end

function s.target5(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return true end
end
function s.operation5(e,tp,eg,ep,ev,re,r,rp)
	-- Effect implementation
end
